spring:
  datasource:

    url: jdbc:mysql://localhost:3306/javacourse

    username: root
    password:


  jpa:
    database: MYSQL
  mvc.view:
    prefix: /WEB-INF/jsp/
    suffix: .jsp
    mvc: resources mapping="/resources/**" location="C:/DEVELOPER/simpleWebRaimondas/src/main/resources/"